---
- name: Show the OS distrubution and version
  ansible.builtin.debug:
    msg: "This server is running {{ ansible_distribution }} version {{ ansible_distribution_version }}"

- name: Perform task only on Ubuntu 22.04
  ansible.builtin.include_tasks:
    file: linux/docker_ubuntu_22_04.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "22.04"

- name: Perform task only on Ubuntu 20.04
  ansible.builtin.include_tasks:
    file: linux/docker_ubuntu_20_04.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"
